### ISSUE TITLE
[Bug]: Not properly working with VersionStrategy::DIFF

### ISSUE THREAD

**Issue by mutschler** [mansoorkhan96/filament-versionable#10]
### What happened?

If you use `VersionStrategy::DIFF` (default) only changed values are stored, so the revision view breaks when you update a filed that wasn't saved in the version before

### How to reproduce the bug

1. Use `VersionStrategy::DIFF` as strategy
2. Create a new Model with `title`, `content` fields
3. Update the `title` => only new title will be saved
4. Update the `content` => only new content will be saved
5. Click "Revisions" and page breaks since `content` is not present on the previous version

### Package Version

0.0.6

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

Linux

### Notes

This isn't directly related to this plugin i guess but to the Diff class you wrote for the upstream package... 

From my understanding: In DIFF Mode you can't directly compare one version to the previous one. You'll have to either load the first version, apply every diff and compare the result to the current one OR go back till you have all keys which where changed in the current version and show them from there

**Comment by mansoorkhan96** [comment]
https://github.com/overtrue/laravel-versionable/issues/56

**Comment by mansoorkhan96** [comment]
@mutschler Have you tried to use `VersionStrategy::SNAPSHOT`, thats what we are going to keep in future.

**Comment by mutschler** [comment]
yeah i've tried that and it works. However i didn't plan to keep full snapshots on the data but only save the changes. Full Snapshots provide too much overhead. Since i've already red upstream that there are plans for dropping `DIFF` strategy i've came up with something else...

However i've spent some time looking into it before and it's actually relatively easy to fix. Actually [revertWithoutSaving](https://github.com/overtrue/laravel-versionable/blob/5.x/src/Version.php#L103-L111) already does most of the things needed by looping through all changes up to the current one, so you'll get the keys you need to have when comparing. I'm gonna check if is still got my solution lying around somewhere if you're interested ;)

**Comment by mansoorkhan96** [comment]
I will check.


@overtrue maybe you should read this.

**Comment by mansoorkhan96** [comment]
@mutschler I am open for a pr or any code block that helps.

**Comment by mutschler** [comment]
i've pushed the code which seemed to work for me here https://github.com/mutschler/laravel-versionable/compare/5.x...patch-2#diff-bc02aa2ebc8787a5e9d2158b017a5ad142a2caff5e24d98e540b7a6442e94fdd not really sure if the if/else part for loading the `$newContents` is really needed but i did it that way for a reason i can't really rememer right now. 

As mentioned before it's more or less the same thing `revertWithoutSaving` does: Load initial data and apply each pach up to the latest previous version to that data, then remove all unneeded keys from the array

**Comment by mansoorkhan96** [comment]
@mutschler I think its fixed and working for you? I am closing for now, feel free to open if you still have issues.
