### ISSUE TITLE
[bug] translatable content not displayed correctly

### ISSUE THREAD

**Issue by nabileisa** [mansoorkhan96/filament-versionable#23]
### What happened?

This is not a bug report as the package does not support [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable) support, but more of of a question.
Currently, when using this with translatable content, the diff view displays all translations as raw json 
see image below.
![image](https://github.com/user-attachments/assets/345c6856-37ac-44e2-b90a-08afa2b678f6)
and it would through an error when stripTags is set to true
```
public function shouldStripTags(): bool
{
        return false;
 }
```
![image](https://github.com/user-attachments/assets/178672c1-8484-4866-8001-213842e62d75)

I was wondering if there is a way to display the data decoded correctly without the json, or you could point me in the right direction I would really appreciate it.

### How to reproduce the bug

Create translatable model and add translations to it. then attempt to view the revisions.

### Package Version

0.0.9

### PHP Version

8.3.8

### Laravel Version

11.20.0

**Comment by a21ns1g4ts** [comment]
Theres an issue with translation

**Comment by mansoorkhan96** [comment]
Hey,
This package does not support arrays or translations for now.
But I am looking to add those features. I might re-write and change things and would be available for Filament v4.

**Comment by mansoorkhan96** [comment]
Hey @abbasmashaddy72 

Please create a separate issue for the problem you are seeing.

> a default revision is being created automatically, even though it's not needed

A default version is created only when you are saving a model and if it does not already have a state in versions table. This is required/need to atleast have the current state of the model before saving the new state. However, you can disable this behaviour by setting `keep_original_version` to false in config file or you can easily override this behaviour in your Models by overriding the methods.
