### ISSUE TITLE
[Bug]: Adding `updated_at` to `$dontVersionable` results in error

### ISSUE THREAD

**Issue by CamilleScholtz** [mansoorkhan96/filament-versionable#4]
### What happened?

I don't really want to track `updated_at`, so I added it to the `$dontVersionable` variable in the model, however when visiting the revisions page I get the following error: `Undefined array key "updated_at"`

### How to reproduce the bug

Add `updated_at` to the `$dontVersionable` variable, edit a record, visit the revisions page.

### Package Version

0.0.4

### PHP Version

8.3.3

### Laravel Version

10.33

### Which operating systems does with happen with?

macOS

**Comment by mansoorkhan96** [comment]
You could just use the `$versionable` property and it would not store the other fields.

Try this:

```php
protected $versionable = ['title', 'content', 'or any other field'];
```

**Comment by mansoorkhan96** [comment]
This package is just a wrapper around [Laravel Versionable](https://github.com/overtrue/laravel-versionable), you should create an issue over there, if you still have issues.

Thanks.

**Comment by CamilleScholtz** [comment]
You are right, this seems to be an issue with versionable.
