### ISSUE TITLE
[Bug]: View revision broken

### ISSUE THREAD

**Issue by Noah-Wilderom** [mansoorkhan96/filament-versionable#8]
### What happened?

I followed the README precisely but the revision view is not loading without any errors in the log.

### How to reproduce the bug

Just follow the README

### Package Version

0.0.5

### PHP Version

8.3.3

### Laravel Version

10.47.0

### Which operating systems does with happen with?

macOS

**Comment by Noah-Wilderom** [comment]
![image](https://github.com/mansoorkhan96/filament-versionable/assets/61543656/615e7a0e-a492-41c2-a0d8-f29771bbfe88)

**Comment by mansoorkhan96** [comment]
Hey

I am constantly using this plugin in a couple of projects with zero issues.

It could be an issue from laravel-versionable, we have been pushing some commits there. Make sure you run composer update and try again.

Thanks.

**Comment by mansoorkhan96** [comment]
@Noah-Wilderom Please make sure to add `protected $versionStrategy = VersionStrategy::SNAPSHOT;` to your Model.
